---
abstract: 'PerlFormance - Benchmark Suite'
author:
  - 'Steffen Schwigon <ss5@renormalist.net>'
build_requires:
  Data::YAML::Reader: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Benchmark-Perl-Formance
requires:
  Benchmark: 0
  Clone: 0
  Config: 0
  Cwd: 0
  Data::DPath: 0
  Data::Dumper: 0
  Data::Structure::Util: 0
  Data::YAML::Writer: 0
  Devel::Platform::Info: 0
  Exporter: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::ShareDir: 0
  File::Temp: 0
  Getopt::Long: 0
  IO::Handle: 0
  IO::Select: 0
  List::Util: 0
  Math::GMP: 0
  Math::MatrixReal: 0
  Moose: 0
  MooseX::Declare: 0
  Mouse: 0
  Storable: 0
  Sys::Hostname: 0
  Time::HiRes: 0
  constant: 0
  integer: 0
  perl: 5.010
  strict: 0
  threads: 0
  threads::shared: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Benchmark-Perl-Formance
  homepage: http://metacpan.org/release/Benchmark-Perl-Formance
  repository: git://github.com/renormalist/Benchmark-Perl-Formance.git
version: 0.31
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/@Basic/GatherDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Basic/PruneCruft'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Basic/ManifestSkip'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Basic/MetaYAML'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Basic/License'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Basic/Readme'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/@Basic/ExtraTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Basic/ExecDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Basic/ShareDir'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Basic/MakeMaker'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Basic/Manifest'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Basic/TestRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Basic/ConfirmRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@Filter/MetaResources'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Filter/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Filter/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@Filter/Git::Describe'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@Filter/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Filter/Git::CheckFor::CorrectBranch'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 1.121820
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300021
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300021
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300021
x_authority: cpan:SCHWIGON
